package moji.com.service_loader_lib;

/* loaded from: classes20.dex */
class MJServiceImplPool {
    public static java.util.Map<java.lang.Class, java.util.Set<java.lang.Object>> a = new java.util.HashMap();

    static {
        a();
    }

    public static void a() {
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJWeatherBoxBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJRainbowBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJFishingBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJFloatBallBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJChargingScreenBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJWeatherPainBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJDangerousDrivingForecastBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJAreaModuleBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJIndexBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJLockScreenBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJFeedBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJIPCModuleBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJWidgetBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJStarGazeBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJWeatherSenceBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJInfluenzaModuleBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJEarthquakeBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJWeatherServiceBaseBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJPostCardBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJSunStrokeBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJAllergyModuleBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJAdModuleBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJSakuraModuleBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJTyphoonModuleBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJWebViewModuleBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJMemberModuleBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJShortTimeBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJWarnBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJNewLiveViewBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJSenceBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJWeatherBaseBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJRedLeavesBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJSkinShopBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJPersonalModuleBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJWeatherCoreBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJCardBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.AliyunEditorBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJ180DayForecastBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJVideoTabModuleBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJDiamonPositionBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJAqiBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJRedPointBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJTabMeBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJForumBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJ40DayForecastBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJSunglowBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJCreditBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJPuddleBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJZodiacBusIndex());
        b(org.greenrobot.eventbus.meta.SubscriberInfoIndex.class, new com.moji.MJUserModuleBusIndex());
        b(com.moji.theme.ThemeRegister.class, new com.moji.mjweather.feed.FeedThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.notificationpermissions.PermissionGuideThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.mjquestionnaire.QuestionnaireThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.zodiac.ZodiacThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.share.view.newview.PlusPanelThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.mjkinsfolk.KinsfolkThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.mjtabme.TabMeThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.earlywarning.WarnThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.card.OpCardThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.camera.CameraThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.base.WeatherBaseThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.mojiweather.area.AreaThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.skinshop.SkinThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.mjpersonalmodule.PersonalThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.member.MemberThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.aqi.AQIThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.mjad.theme.AdThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.forum.ForumThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.mjweather.ipc.IPCThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.sence.scenestore.SceneThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.rainclould.RainCloudThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.newliveview.LiveViewThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.sakura.SakuraThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.postcard.PostCardThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.index.IndexThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.user.UserThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.redleaves.RedLeavesThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.condition.ConditionThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.mjweather.main.MainThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.theme.MJDayNightThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.videoshopcard.ShopThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.mjweathercorrect.WeatherCorrectThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.mjweather.typhoon.newversion.TyphoonThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.mj180dayforecast.Weather180DaysThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.mj40dayforecast.Days40MainThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.ski.SkiThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.influenza.InfluenzaThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.mjtravel.CityTravelThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.days40.Days40ThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.mjlockscreen.LockScreenThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new moji.com.mjweatherservicebase.WeatherServiceThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.dangerousdrivingforecast.DangerousDrivingThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.shorttime.ui.ShortTimeThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.mjallergy.AllergyThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.sunglow.SunglowThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.mjfishing.FishingThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.credit.CreditThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.earthquake.ui.EarthquakeThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.diamon.DiamondThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.DrawLotsThemeRegister());
        b(com.moji.theme.ThemeRegister.class, new com.moji.weatherpain.WeatherPainThemeRegister());
        b(com.moji.appwidget.core.SkinProvider.class, new com.moji.appwidget.widget_2019.windbell.SkinProviderWindBell());
        b(com.moji.appwidget.core.SkinProvider.class, new com.moji.appwidget.widget_2019.SkinProvider800602());
        b(com.moji.appwidget.core.SkinProvider.class, new com.moji.appwidget.widget_2019.dualcity.SkinProviderDualCity());
        b(com.moji.appwidget.core.SkinProvider.class, new com.moji.appwidget.widget_2019.SkinProvider800601());
        b(com.moji.appwidget.core.SkinProvider.class, new com.moji.appwidget.widget_2019.SkinProvider8026());
        b(com.moji.appwidget.core.SkinProvider.class, new com.moji.appwidget.widget_2019.SkinProviderDragonBoat());
        b(com.moji.api.APILifeCycle.class, new com.moji.mjweather.helper.ShareAPILifeCycle());
        b(com.moji.api.APILifeCycle.class, new com.moji.novice.tutorial.api.IAPIMemberAdTutorialLifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.register.MSALifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.sence.scenestore.model.impl.ISceneSwitchAPILifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.weathersence.api.SceneAPILifeCycle());
        b(com.moji.api.APILifeCycle.class, new com.moji.earthquake.manager.IEarthquakeAPILifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.mjweather.setting.api.SettingAPILifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.mjweather.tabmember.api.MemberLifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.mjweather.feed.INewLiveAPILifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.sence.scenestore.model.impl.IFreeSceneAPILifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.newliveview.camera.impl.ICompressApiLifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.mjweather.share.WeatherAPILifeCycle());
        b(com.moji.api.APILifeCycle.class, new com.moji.statistics.upload.api.StatisticsUploadLifeCycle());
        b(com.moji.api.APILifeCycle.class, new com.moji.account.data.impl.IAccountLifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.mjad.provide.AdAPILifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.mjlockscreen.LockScreenAPILifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.user.homepage.INewAlertAPILifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.weathersence.predistributed.impl.ISceneUpdateLifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.mjweather.weathercorrect.WeatherBgAdAPILifeCycle());
        b(com.moji.api.APILifeCycle.class, new com.moji.mjweathercorrect.impl.IWeaterCorrectModeLifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.mjcommand.CommandAPILifeCycle());
        b(com.moji.api.APILifeCycle.class, new com.moji.weathersence.data.impl.ISceneDataLifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.mjweather.weather.window.location.guide.LocationGuideAPILifeCycle());
        b(com.moji.api.APILifeCycle.class, new com.moji.appwidget.api.IWidgetLifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.mjlunarphase.api.PhaseAPILifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.mjchargingscreen.api.ChargingScreenAPILifecycle());
        b(com.moji.api.APILifeCycle.class, new com.moji.credit.api.CreditAPILifeCycle());
        b(com.moji.api.APILifeCycle.class, new com.moji.mjfloatball.api.JCAPILifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.weathersence.data.impl.IWeaterSceneLifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.mjweather.api.AppAPILifeCycle());
        b(com.moji.api.APILifeCycle.class, new com.moji.userportrait.UserPortraitLifeCycle());
        b(com.moji.api.APILifeCycle.class, new com.moji.shorttime.app.IShortTimeAPILifecycle());
        b(com.moji.api.APILifeCycle.class, new com.moji.weathersence.theme.impl.ILocalSceneLifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.mjweather.feed.dress.api.DressAPILifecycle());
        b(com.moji.api.APILifeCycle.class, new com.moji.mjfloatball.api.FloatBallAPILifeCycleHelper());
        b(com.moji.api.APILifeCycle.class, new com.moji.mjtabme.api.TabMeAPILifeCycle());
        b(com.moji.api.APILifeCycle.class, new com.moji.mjquestionnaire.app.IQuestionnaireAPILifecycle());
        b(com.moji.iapi.router.IRouterInterceptor.class, new com.moji.index.jump.FlutterInterceptor());
        b(com.moji.skinshop.entiy.ILocalWidget.class, new com.moji.skinshop.widget.WidgetWindBell());
        b(com.moji.skinshop.entiy.ILocalWidget.class, new com.moji.skinshop.widget.Widget800602());
        b(com.moji.skinshop.entiy.ILocalWidget.class, new com.moji.skinshop.widget.WidgetDualCity());
        b(com.moji.skinshop.entiy.ILocalWidget.class, new com.moji.skinshop.widget.WidgetDragonBoat());
        b(com.moji.skinshop.entiy.ILocalWidget.class, new com.moji.skinshop.widget.Widget8026());
    }

    public static void b(java.lang.Class cls, java.lang.Object obj) {
        java.util.Set<java.lang.Object> set = a.get(cls);
        if (set == null) {
            set = new java.util.HashSet<>();
        }
        set.add(obj);
        a.put(cls, set);
    }
}
