package com.getui.gtc.extension.distribution.gbd.d;

/* loaded from: classes22.dex */
public final class h {
    public static long B;
    public static java.util.Map<java.lang.String, java.lang.String> I;
    public static java.lang.String K;
    public static java.lang.String M;
    public static java.lang.String N;
    public static java.lang.String P;
    public static long R;
    public static long S;
    public static long T;
    public static int U;
    public static long V;
    public static long W;
    public static long X;
    public static long Y;
    public static java.lang.String Z;
    public static com.getui.gtc.extension.distribution.gbd.f.a a;
    public static java.util.List<java.lang.String> aC;
    public static java.lang.String aH;
    public static int aK;
    public static boolean aL;
    public static boolean aN;
    public static boolean aO;
    public static long aP;
    public static boolean aR;
    public static java.lang.String aS;
    public static long aT;
    public static long aU;
    public static int aZ;
    public static long aa;
    public static long ab;
    public static long ac;
    public static int ad;
    public static long af;
    public static java.lang.String ag;
    public static java.lang.String au;
    public static java.lang.String av;
    public static java.lang.String aw;
    public static java.lang.String ax;
    public static java.lang.String ay;
    public static com.getui.gtc.extension.distribution.gbd.e.a b;
    public static long bm;
    public static long bo;
    public static android.net.wifi.WifiManager c;
    public static java.net.ServerSocket g;
    public static boolean i;
    public static long j;
    public static long k;
    public static java.lang.String l;
    public static long r;
    public static java.util.concurrent.atomic.AtomicBoolean d = new java.util.concurrent.atomic.AtomicBoolean(true);
    public static java.util.concurrent.atomic.AtomicBoolean e = new java.util.concurrent.atomic.AtomicBoolean(true);
    public static java.util.concurrent.atomic.AtomicBoolean f = new java.util.concurrent.atomic.AtomicBoolean(true);
    public static final int h = android.os.Build.VERSION.SDK_INT;
    public static long m = 0;
    public static long n = 0;
    public static int o = 0;
    public static long p = 0;
    public static long q = 0;

    /* renamed from: s, reason: collision with root package name */
    public static java.lang.String f325s = "none";
    public static java.lang.String t = "";
    public static java.lang.String u = "";
    public static long v = 0;
    public static long w = 0;
    public static long x = 0;
    public static java.lang.String y = "";
    public static java.util.concurrent.ConcurrentHashMap<java.lang.String, java.util.concurrent.ConcurrentHashMap<java.lang.String, java.lang.String>> z = new java.util.concurrent.ConcurrentHashMap<>();
    public static java.util.concurrent.CopyOnWriteArrayList<java.lang.Integer> A = new java.util.concurrent.CopyOnWriteArrayList<>();
    public static java.util.List<java.lang.Long> C = new java.util.ArrayList();
    public static long D = 0;
    public static long E = 0;
    public static java.util.Map<java.lang.String, com.getui.gtc.extension.distribution.gbd.c.a> F = new java.util.HashMap();
    public static java.util.Map<java.lang.String, java.lang.Long> G = new java.util.HashMap();
    public static int H = 0;
    public static long J = 0;
    public static java.util.concurrent.CopyOnWriteArrayList<java.lang.Integer> L = new java.util.concurrent.CopyOnWriteArrayList<>();
    public static long O = 0;
    public static long Q = 0;
    public static java.lang.String ae = "";
    public static long ah = 0;
    public static java.lang.String ai = "";
    public static long aj = 0;
    public static long ak = 0;
    public static long al = 0;
    public static java.lang.String am = "";
    public static long an = 0;
    public static java.lang.String ao = "";
    public static java.lang.String ap = "";
    public static java.lang.String aq = "IKOVemN2qbN1H8oLTSin+A==";
    public static java.lang.String ar = "JZ3K/+Lc+pARpAzWUz/1AA==";
    public static java.lang.String as = "JZ3K/+Lc+pARpAzWUz/1AA==";
    public static java.util.List<java.lang.String> at = new java.util.ArrayList();
    public static boolean az = false;
    public static boolean aA = false;
    public static byte[] aB = null;
    public static long aD = 0;
    public static long aE = 0;
    public static long aF = 0;
    public static long aG = 0;
    public static boolean aI = false;
    public static int aJ = -1;
    public static java.lang.String aM = "";
    public static int aQ = -1;
    public static java.lang.String aV = "";
    public static long aW = 0;
    public static java.lang.String aX = "";
    public static java.lang.String aY = "";
    public static long ba = 0;
    public static int bb = 0;
    public static long bc = 0;
    public static long bd = 0;
    public static long be = 0;
    public static long bf = 0;
    public static long bg = 0;
    public static long bh = 0;
    public static long bi = 0;
    public static long bj = 0;
    public static long bk = 0;
    public static long bl = 0;
    public static boolean bn = false;
}
