package com.igexin.push.config;

/* loaded from: classes23.dex */
public final class d {
    public static int A = 200;
    public static java.lang.String B = "oppo r9,oppo A59,oppo a37";
    public static java.lang.String C = "none";
    public static boolean D = false;
    public static boolean E = true;
    public static java.lang.String F = "applk.cn";
    public static java.lang.String G = "huawei,honor";
    public static boolean H = true;
    public static boolean I = true;
    public static boolean J = true;
    public static boolean K = true;
    public static boolean L = true;
    public static java.lang.String M = "";
    public static int N = 10;
    public static long O = 2048;
    public static java.lang.String P = "vivo|26~100";
    public static boolean Q = false;
    public static boolean T = false;
    public static long a = 600;
    public static int b = 0;
    public static int c = 0;
    public static long d = 0;
    public static int e = 0;
    public static int f = 0;
    public static boolean g = true;
    public static boolean h = true;
    public static boolean i = true;
    public static boolean j = true;
    public static boolean k = true;
    public static boolean l = true;
    public static boolean m = true;
    public static boolean n = true;
    public static boolean o = true;
    public static boolean p = false;
    public static boolean q = true;
    public static long r = 72000000;

    /* renamed from: s, reason: collision with root package name */
    public static int f385s = 150;
    public static int t = 80;
    public static long u = 7200000;
    public static long v = 7200000;
    public static java.lang.String w = "";
    public static int x = 3;
    public static long y = 600000;
    public static int z = 1;
    public static java.lang.Boolean R = java.lang.Boolean.FALSE;
    public static long S = com.anythink.expressad.d.a.b.aT;
    public static boolean U = true;
    public static boolean V = false;
    public static long W = com.anythink.expressad.d.a.b.aT;
    public static boolean X = true;
    public static boolean Y = false;
    public static long Z = 500;
    public static int aa = 4;
    public static boolean ab = false;
    public static boolean ac = false;
    public static boolean ad = false;
    public static boolean ae = false;
    public static boolean af = false;
    public static int ag = 5;
    public static boolean ah = false;
    public static boolean ai = false;
    public static java.lang.String aj = "5|2";
    public static boolean ak = false;
    public static java.lang.String al = com.igexin.assist.util.AssistUtils.BRAND_HW;
    public static boolean am = false;
}
